#!/bin/sh

# Define my_exit function
# We need to create a file that contains the return code of
# this process because Condor-G can't retrieve the exit code of a
# job submitted to GT2. So instead we write the exit code to a file
# and transfer the file back to the submit machine where it can be
# read to determine the true return code of the job. This is a
# lightweight replacement for kickstart.
O_WORK_DIR=`pwd` # Original work directory where rc file will be created
echo "99 Unknown failure" > ${O_WORK_DIR}/rc
my_exit ()
{
	rc=$1
	msg=$2
	echo $msg
	# Exit code 1 is a parameter error
	if [ "$rc" = "1" ]; then usage; fi
	echo "$rc $msg" > ${O_WORK_DIR}/rc
	exit $rc
}

# Usage
CMD=`basename $0`
usage ()
{
	echo """Usage: $CMD -installPath <path>

OPTIONS

  -installPath <path>
      The path to install the Condor executables.
"""
}

INSTALL_PATH=""

while [ $# -ge 1 ]; do
	case $1 in
		-installPath) INSTALL_PATH=$2 ;;
		*) my_exit 1 "Invalid argument $1" ;;
	esac
	shift
	shift
done

if [ -z "${INSTALL_PATH}" ]; then
	my_exit 1 "Missing -installPath"
fi

# Remove installation directory
if [ -d ${INSTALL_PATH} ]; then
	rm -rf ${INSTALL_PATH}
fi

my_exit 0