#!/bin/sh

# Define my_exit function
# We need to create a file that contains the return code of
# this process because Condor-G can't retrieve the exit code of a
# job submitted to GT2. So instead we write the exit code to a file
# and transfer the file back to the submit machine where it can be
# read to determine the true return code of the job. This is a
# lightweight replacement for kickstart.
O_WORK_DIR=`pwd` # Original work directory where rc file will be created
my_exit ()
{
	rc=$1
	msg=$2
	echo $msg
	# Exit code 1 is a parameter error
	if [ "$rc" = "1" ]; then usage; fi
	echo "$rc $msg" > $O_WORK_DIR/rc
	exit $rc
}

# Usage
CMD=`basename $0`
usage ()
{
	echo """Usage: $CMD -installPath <path> [-version <version> | -package <tar.gz>] -url <url> [-url <url> ...]

OPTIONS

  -installPath <path>
      The path to install the Condor executables.
  -version <version>
      The version of Condor to use. Ex: 7.0.0
  -package <tar.gz>
      The tar.gz archive to download. Default is gathered from system info.
      Ex: 7.0.0-x86-Linux-2.4-glibc2.3.tar.gz
  -url <url>
      The server URL where the glidein jobs are hosted. Protocols supported
      include: http, https, ftp, and gsiftp.
"""
}

SERVER_URLS=""
INSTALL_PATH=""
VERSION=""
PACKAGE=""

while [ $# -ge 1 ]; do
	case $1 in
		-installPath) INSTALL_PATH=$2 ;;
		-version) VERSION=$2 ;;
		-package) PACKAGE=$2 ;;
		-url) SERVER_URLS="${SERVER_URLS} $2" ;;
		*) my_exit 1 "Unknown argument: $1" ;;
	esac
	shift
	shift
done

# Must specify path
if [ -z "${INSTALL_PATH}" ]; then
	my_exit 1 "Must specify -path"
fi
if ! echo ${INSTALL_PATH} | grep -q -E "^/"; then
	my_exit 1 "Invalid path ${INSTALL_PATH}"
fi

# Need at least one server url
if [ -z "${SERVER_URLS}" ]; then
	my_exit 1 "Must specify at least one -url"
fi
for URL in ${SERVER_URLS}; do
	if ! echo $URL | grep -q -E "(^gsiftp)|(^http)|(^ftp)"; then
		my_exit 1 "Invalid URL: $URL"
	fi
done

# Must specify either package or version
if [ -z "$PACKAGE" ] && [ -z "$VERSION" ]; then
	my_exit 1 "Must specify -package or -version"
fi
if [ ! -z "$PACKAGE" ] && [ ! -z "$VERSION" ]; then
	my_exit 1 "Must specify either -package or -version"
fi
if [ ! -z "$VERSION" ]; then
	if ! echo $VERSION | grep -q -E "^[0-9]+[.][0-9]+[.][0-9]+$"; then
		my_exit 1 "Invalid Condor version: $VERSION"
	fi
fi

# Check environment
if [ -z "${GLOBUS_LOCATION}" ]; then
	my_exit 2 "GLOBUS_LOCATION environment variable not set"
fi

# If user specified version only, then determine package
if [ -z "$PACKAGE" ]; then

	# Determine package name
	os=`uname -s`
	case $os in
		Linux)
			# kernel and major versions only
			osver=`uname -r | cut -f1,2 -d.`
			arch=`uname -m`
			# change all the i486, i586, i686, etc to x86
			case $arch in
				i*86) arch="x86" ;;
			esac
			# glibc version, just major.minor
			glibc=`ldd --version | head -1 | cut -f4 -d" " | cut -f1,2 -d.`
			PACKAGE="${VERSION}-${arch}-${os}-${osver}-glibc${glibc}.tar.gz"
		;;
		SunOS)
			os="Solaris"
			arch=`uname -p`
			osver=`uname -r`
			case $osver in
				5.6) osver="2.6" ;;
				5.7) osver="7" ;;
				5.8) osver="8" ;;
				5.9) osver="9" ;;
				5.10) osver="10" ;;
			esac
			PACKAGE="${VERSION}-${arch}-${os}-${osver}.tar.gz"
		;;
		AIX)
			arch=`uname -p`
			osver="`uname -v`.`uname -r`"
			PACKAGE="${VERSION}-${arch}-${os}-${osver}.tar.gz"
		;;
		Darwin)
			os="MacOSX"
			arch=`uname -p`
			case $arch in
				powerpc64) arch="ppc64" ;;
				powerpc) arch="ppc" ;;
				i*86) arch="x86" ;;
			esac
			osver=`uname -r`
			case $osver in
				5.*) osver="10.1" ;;
				6.*) osver="10.2" ;;
				7.*) osver="10.3" ;;
				8.*) osver="10.4" ;;
				9.*) osver="10.5" ;;
				*) osver="unknown" ;;
			esac
			PACKAGE="${VERSION}-${arch}-${os}-${osver}.tar.gz"
		;;
		HP-UX)
			# arch will be either ia64 or PA-RISC
			arch=`uname -m`
			if [ "$arch" != "ia64" ]; then
				arch="PA-RISC"
			fi
			# uname -r => B.11.00
			osver=`uname -r | cut -f2,3 -d.`
			PACKAGE="${VERSION}-${arch}-${os}-${osver}.tar.gz"
		;;
		FreeBSD)
			arch=`uname -p`
			case $arch in
				i*86) arch="x86" ;;
			esac
			# Major version only
			# uname -r => 6.1-RELEASE-p15
			osver=`uname -r | cut -f1 -d- | cut -f1 -d.`
			PACKAGE="${VERSION}-${arch}-${os}-${osver}.tar.gz"
		;;
		*)
			arch=`uname -p`
			osver=`uname -r`
			PACKAGE="${VERSION}-${arch}-${os}-${osver}.tar.gz"
		;;
	esac
fi

# Download Condor package from one of the servers
PACKAGE_PATH=`pwd`/package.tar.gz
GUC=${GLOBUS_LOCATION}/bin/globus-url-copy
if [ ! -x $GUC ]; then
	my_exit 2 "Unable to locate globus-url-copy"
fi
for URL in $SERVER_URLS; do
	
	PACKAGE_URL=$URL/$PACKAGE
	
	# Try globus-url-copy first
	$GUC $PACKAGE_URL file:$PACKAGE_PATH
	rc=$?;
	
	# If globus-url-copy fails and the url is http or ftp, then try wget
	if [ $rc != 0 ] || [ ! -f $PACKAGE_PATH ] && 
	echo $URL | grep -q -E '(^http)|(^ftp)'; then
		wget -q -O $PACKAGE_PATH $PACKAGE_URL
		rc=$?;
	fi

	# Stop if we were successful
	if [ $rc = 0 ] && [ -f $PACKAGE_PATH ]; then 
		# Break out of loop
		break
	else
		# Remove any zero-length files that may have been created
		rm -f $PACKAGE_PATH
	fi
done

# If package could not be downloaded from any server
if [ ! -f ${PACKAGE_PATH} ]; then
	my_exit 3 "Failed to retrieve $PACKAGE"
fi

# Make install directory if it doesn't exist
if [ ! -d ${INSTALL_PATH} ]; then
	mkdir -p ${INSTALL_PATH}
	if [ ! -d ${INSTALL_PATH} ]; then
		my_exit 4 "Unable to create remote install directory: ${INSTALL_PATH}"
	fi
fi

# Install package
cd ${INSTALL_PATH}
if ! tar -xzf ${PACKAGE_PATH}; then
	my_exit 5 "Failed to install Condor glidein package"
fi

# Exit successfully
my_exit 0
