#!/usr/bin/env python
#
# Copyright 2007-2009 University Of Southern California
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os, time, datetime, calendar, popen2, sys, getopt, signal, pwd, grp


# Set some defaults
OUTPUT="/dev/stdout"
INTERVAL=300
MAXSIZE=1024
POOL=None
LOG=None
RRD=None


# Print usage message
def usage():
	print """Usage: %s [-o FILE] [-i INTERVAL] [-m MAXSIZE]

This script periodically prints the state and activity status of resources in a
Condor pool. The output is printed in Netlogger format.

OPTIONS

   -o | --output FILE
      The file to write NetLogger output to. Defaults to %s.
   -i | --interval SECONDS
      The number of seconds to wait between logging events. Defaults to %d.
   -m | --maxsize KB
      The maximum output file size in KB. Defaults to %d KB (1 MB, or ~2 weeks
      using 5 min interval). When the log reaches this size, its name gets the 
      date appended onto it and a new log is started.
   -p | --pool HOST
      The pool to query. The machine from which this service runs should have
      READ permissions for the pool. Defaults to the pool currently set in the
      local condor_config file.
   -l | --log FILE
      The log file for debugging output. Defaults to stdout.
   -r | --rrd FILE
      The rrdtool database to use.
   -h | --help
      Prints this usage message.
""" % (os.path.basename(sys.argv[0]), OUTPUT, INTERVAL, MAXSIZE)


# Print an informational message
def info(message):
	print datetime.datetime.now().isoformat(), message


# Get the value of a configuration parameter from condor
def condor_config_val(key):
	ccv = popen2.Popen4("condor_config_val %s" % key)
	val = ccv.fromchild.readline() ; ccv.fromchild.readlines()
	if ccv.wait() == 0:
		return val.strip()
	else:
		return None


# Get the condor user id's UID and GID
def get_condor_ids():
	# Try condor's CONDOR_IDS config val first
	uidgid = condor_config_val("CONDOR_IDS")
	if uidgid:
		ids = uidgid.split(".")
		ids[0] = int(ids[0])
		ids[1] = int(ids[1])
		return ids
	else:
		info("CONDOR_IDS not set")
		# Look for 'condor' user
		try:
			pw = pwd.getpwnam("condor")
			return pw[2:4]
		except KeyError:
			info("Unable to get UID/GID for user 'condor'")
			return None


# Get job statistics from condor_q
def condor_q():
	# Initialize stats
	jstatn = ['unexpanded','idle','running','removed','completed','held','submission_error']
	jstats = {'unexpanded':0, 'idle':0, 'running':0, 
			  'removed':0, 'completed':0, 'held':0, 'total':0, 'submission_error':0}
	
	# Run condor_q
	cmd = "%s/bin/condor_q" % CONDOR_HOME
	if POOL: cmd += " -pool %s -global" % POOL
	cmd += " -format '%s\n' JobStatus"
	cq = popen2.Popen4(cmd)
	stats = cq.fromchild.readlines()
	rc = cq.wait()
	if rc == 0:
		for stat in stats:
			if 'empty' in stat: continue
			try:
				stat = int(stat)
				jstats[jstatn[stat]] += 1
			except ValueError:
				print stats
				return None
	elif rc == 256 and 'empty' in stats[0]:
		pass
	else:
		print stats
		return None

	# Set the total number of jobs
	jstats['total'] = reduce(lambda x,y: x+y, jstats.values())
	
	return jstats


# Get machine statistics from condor_status	
def condor_status():
	# Initialize stats
	sstats = {'owner':0, 'unclaimed':0, 'matched':0, 'claimed':0, 
			  'preempting':0, 'backfill':0, 'total':0}
	
	# Run condor_status
	cmd = "%s/bin/condor_status" % CONDOR_HOME
	if POOL:
		cmd += " -pool %s" % POOL
	cmd += " -format '%s\n' State"
	cs = popen2.Popen4(cmd)
	stats = cs.fromchild.readlines()
	if cs.wait() ==0:
		for stat in stats:
			stat = stat[:-1].lower()
			if stat: sstats[stat] += 1
	else:
		print stats
		return None

	# Add up the total number of slots
	sstats['total'] = reduce(lambda x,y: x+y, sstats.values())
	
	return sstats


# Trap signals and exit gracefully
def trap(sig, frame):
	info("Shutting down...")
	sys.exit(0)


# Create rrdtool database
def create_rrd(rrd, interval):
	heartbeat = interval * 4
	DS = [
		"DS:jobs_running:GAUGE:%d:0:1000000" % heartbeat,
		"DS:jobs_idle:GAUGE:%d:0:1000000" % heartbeat,
		"DS:slots_claimed:GAUGE:%d:0:1000000" % heartbeat,
		"DS:slots_unclaimed:GAUGE:%d:0:1000000" % heartbeat
	]
	hour = 60*60
	day = 24*hour
	week = 7*day
	RRA = [
		"RRA:AVERAGE:0.5:1:%d" % (7*day/interval), # keep 1 week of raw timesteps

		"RRA:AVERAGE:0.5:%d:%d" % ((hour/interval),(24*7*60)), # keep 60 days of hourly avg/min/max
		"RRA:MIN:0.5:%d:%d" % ((hour/interval),(24*7*60)),
		"RRA:MAX:0.5:%d:%d" % ((hour/interval),(24*7*60)),
		
		"RRA:AVERAGE:0.5:%d:%d" % ((day/interval),365), # keep 1 year of daily avg/min/max
		"RRA:MIN:0.5:%d:%d" % ((day/interval),365),
		"RRA:MAX:0.5:%d:%d" % ((day/interval),365)
	]

	rrdtool.create(rrd, '--step', '%d' % interval, *(DS+RRA))


# Make sure existing rrdtool database will work with desired settings
def check_rrd(rrd, interval):
	info = rrdtool.info(rrd)
	if info['step'] != interval:
		raise Exception("RRD step size %d not equal to interval %d" % (info['step'],interval))


def update_rrd(rrd, dt, jstats, sstats):
	try:
		ts = calendar.timegm(dt.timetuple())
		rrdtool.update(rrd, "%d:%d:%d:%d:%d" % (ts, jstats['running'], jstats['idle'], sstats['claimed'], sstats['unclaimed']))
	except Exception, e:
		info("Unable to update rrd: %s" % e)


# Install signal handlers
signal.signal(signal.SIGTERM, trap)
signal.signal(signal.SIGINT, trap)
signal.signal(signal.SIGHUP, trap)
signal.signal(signal.SIGUSR1, trap)
signal.signal(signal.SIGUSR2, trap)


# If running as root, set effective uid & gid to condor user
if os.getuid()==0:
	ids = get_condor_ids()
	if ids == None:
		info("No condor user found")
		info("Cannot run command as root")
		sys.exit(1)
	os.setgid(ids[1])
	os.setuid(ids[0])

# Set umask so that any files created will be readable by all
os.umask(0022)


# Parse arguments
try:
	opts, args = getopt.getopt(sys.argv[1:], "hl:o:i:m:p:r:", 
					["help","log=","output=","interval=","maxsize=","pool=","rrd="])
except getopt.GetoptError, err:
	# print help information and exit:
	print str(err) # will print something like "option -a not recognized"
	sys.exit(3)
for o, a in opts:
	if o in ("-h","--help"):
		usage()
		sys.exit(0)
	elif o in ("-o","--output"):
		OUTPUT=a
	elif o in ("-l","--log"):
		LOG=a
	elif o in ("-i","--interval"):
		INTERVAL=int(a)
	elif o in ("-m","--maxsize"):
		MAXSIZE=int(a)
	elif o in ("-p","--pool"):
		POOL=a
	elif o in ("-r","--rrd"):
		RRD=a
	else:
		info("unhandled argument: %s" % o)
		sys.exit(5)


# Redirect output to log
if LOG is not None:
	try:
		log = open(LOG,"a",1)
		sys.stdout.close()
		sys.stderr.close()
		sys.stdout = log
		sys.stderr = log
	except IOError, err:
		info(str(err))
		sys.exit(2)


# Import rrdtool
if RRD is not None:
	try:
		import rrdtool
	except:
		info("Unable to load rrdtool")
		RRD = None


# Find CONDOR_HOME
try:
	CONDOR_HOME = os.environ['CONDOR_HOME']
except KeyError, err:
	print "Please set CONDOR_HOME"
	sys.exit(3)


# Welcome message
info("Pool status monitor starting...")


# Create or check rrd
if RRD is not None:
	if os.path.exists(RRD):
		check_rrd(RRD, INTERVAL)
	else:
		create_rrd(RRD, INTERVAL)


# Loop forever collecting status
firstime = True
while True:

	# Go to sleep for a while
	if not firstime:
		time.sleep(INTERVAL)
	firstime = False

	# Get job status
	jstats = condor_q()
	if not jstats:
		info("condor_q failed")
		continue

	# Get machine status
	sstats = condor_status()
	if not sstats:
		info("condor_status failed")
		continue

	# Get timestamp
	now = datetime.datetime.utcnow()
	ts = now.strftime("%Y-%m-%dT%H:%M:%S")
	ts += ".%06dZ" % now.microsecond # For older pythons without %f

	# Create record
	rec = "ts=%s event=condor.status" % ts
	for k,v in sstats.items():
		rec += " machine.%s=%s" % (k,v)
	for k,v in jstats.items():
		rec += " job.%s=%s" % (k,v)

	# Rotate log if necessary
	if os.path.isfile(OUTPUT):
		st = os.stat(OUTPUT)
		if (st.st_size/1024) >= MAXSIZE:
			stamp = now.strftime("%Y%m%d")
			os.rename(OUTPUT,OUTPUT+"."+stamp)
	
	# Write output record
	try:
		output = open(OUTPUT,"a",1)
		output.write(rec+"\n")
		output.close()
	except IOError, err:
		info(str(err))
		sys.exit(4)
	
	# Update rrd
	if RRD is not None:
		update_rrd(RRD, now, jstats, sstats)


