#!/bin/sh
#
# Copyright 2007-2009 University Of Southern California
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This script copys glidein_run to a temporary file and executes it from there.
# This bizzare procedure is required because on some sites when a job is
# deleted the directory containing the job script is removed before the script
# is finished running. By copying the script we want to run we are able to
# clean up everything. 

echo "Starting glidein_run..."
if [ ! -z "$SCRATCH_DIRECTORY" ]; then
	cd $SCRATCH_DIRECTORY
fi
SCRIPT=/tmp/glidein_run.$$
cat glidein_run > $SCRIPT
chmod 700 $SCRIPT
exec $SCRIPT "$@"