#!/bin/sh
#
# Copyright 2007-2009 University Of Southern California
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Create status file if not interactive
if [ ! -t 0 ]; then
	STATUS=`pwd`/status
	touch $STATUS
fi

# Write error message to stderr and to status file if not interactive
error ()
{
	echo "$@" >&2
	if [ ! -t 0 ]; then
		echo "$@" >>$STATUS
	fi
}

# Usage
CMD=`basename $0`
usage ()
{
	error """Usage: $CMD OPTIONS REQUIRED

REQUIRED

  -i | -installPath <path>
      The path where the Condor executables are installed.
      
OPTIONS

  -h | -help
      Display this usage message.
"""
}

INSTALL_PATH=""

while [ $# -ge 1 ]; do
	case $1 in
		-i | -installPath) INSTALL_PATH=$2 ;;
		-h | -help) usage ; exit 1 ;;
		*) error "Invalid argument $1" ; exit 1 ;;
	esac
	shift
	shift
done

# Check arguments
if [ -z "${INSTALL_PATH}" ]; then
	error "Missing -installPath"
	exit 1
fi
INSTALL_PATH=`eval "echo ${INSTALL_PATH}"`

# Remove installation directory
if [ -d ${INSTALL_PATH} ]; then
	rm -rf ${INSTALL_PATH}
	rc=$?
	if [ $rc -ne 0 ]; then
		error "Unable to delete install directory: ${INSTALL_PATH}"
		exit 1
	fi
fi

exit 0