#!/bin/sh

# Usage
CMD=`basename $0`
usage ()
{
	echo """Usage: $CMD OPTIONS REQUIRED

REQUIRED

  -i | -installPath <path>
      The path where the Condor executables are installed.
  -l | -localPath <path>
      The path where log files have been written.
      
OPTIONS

  -h | -help
      Display this usage message.
""" >&2
}

INSTALL_PATH=""

while [ $# -ge 1 ]; do
	case $1 in
		-i | -installPath) INSTALL_PATH=$2 ;;
		-l | -localPath) LOCAL_PATH=$2 ;;
		-h | -help) usage ; exit 1 ;;
		*) echo "Invalid argument $1" >&2 ; exit 1 ;;
	esac
	shift
	shift
done

# Check arguments
if [ -z "${INSTALL_PATH}" ]; then
	echo "Missing -installPath" >&2
	exit 1
fi
INSTALL_PATH=`eval "echo ${INSTALL_PATH}"`

if [ -z "${LOCAL_PATH}" ]; then
	echo "Missing -localPath" >&2
	exit 1
fi
LOCAL_PATH=`eval "echo ${LOCAL_PATH}"`

# Remove installation directory
if [ -d ${INSTALL_PATH} ]; then
	rm -rf ${INSTALL_PATH}
	rc=$?
	if [ $rc -ne 0 ]; then
		echo "Unable to delete install directory: ${INSTALL_PATH}" >&2
		exit 1
	fi
fi

# Remove log directory if it exists
if [ -d ${LOCAL_PATH} ]; then
	rm -rf ${LOCAL_PATH}
	# The local path may be local to each node, so we may not
	# be able to delete it here
fi

exit 0