#!/bin/sh

# Usage
CMD=`basename $0`
usage ()
{
	echo """Usage: $CMD OPTIONS -i <path> (-u <url> | (-v <version> | -p <package>) -r <url>)

OPTIONS

  -i | -installPath <path>
      The path to install the Condor executables.
  -v | -condorVersion <version>
      The version of Condor to use. Ex: 7.0.0. Specify either -condorVersion
      or -condorPackage, but not both.
  -p | -condorPackage <tar.gz>
      The tar.gz archive to download. Default is gathered from system info.
      Ex: 7.0.0-x86-Linux-2.4-glibc2.3.tar.gz. Specify either -condorVersion
      or -condorPackage, but not both.
  -r | -rls <url>
	  The replica location service URL where the package name can be looked
	  up to find an appropriate replica of the binary worker node package to
	  download. Specify either -rls or -url, but not both.
  -u | -url <url>
      The server URL of the binary worker node package. Protocols supported
      include: http, https, ftp, and gsiftp. Specify either -rls or -url,
      but not both.
  -h | -help
      Display this usage message
""" >&2
}

INSTALL_PATH=""
VERSION=""
PACKAGE=""
PACKAGE_URL=""
RLS_URL=""

while [ $# -ge 1 ]; do
	case $1 in
		-i | -installPath) INSTALL_PATH=$2 ;;
		-v | -condorVersion) VERSION=$2 ;;
		-p | -condorPackage) PACKAGE=$2 ;;
		-u | -url) PACKAGE_URL=$2 ;;
		-r | -rls) RLS_URL=$2 ;;
		-h | -help) usage ; exit 1 ;;
		*) echo "Unknown argument: $1" >&2 ; exit 1 ;;
	esac
	shift
	shift
done

# Must specify path
if [ -z "${INSTALL_PATH}" ]; then
	echo "Must specify -installPath" >&2
	exit 1
fi
if ! echo ${INSTALL_PATH} | grep -q -E "^/"; then
	echo "Install path must be absolute: ${INSTALL_PATH}" >&2
	exit 1
fi

if [ -z "${PACKAGE_URL}" ] && [ -z "${RLS_URL}" ]; then
	echo "Please specify either -rls or -url" >&2
	exit 1
fi

# If we are using RLS
if [ -z "${PACKAGE_URL}" ]; then

	# Must specify either package or version
	if [ -z "$PACKAGE" ] && [ -z "$VERSION" ]; then
		echo "Must specify -condorPackage or -condorVersion" >&2
		exit 1
	fi
	if [ ! -z "$PACKAGE" ] && [ ! -z "$VERSION" ]; then
		echo "Must specify either -condorPackage or -condorVersion" >&2
		exit 1
	fi
	if [ ! -z "$VERSION" ]; then
		if ! echo "$VERSION" | grep -q -E "^[0-9]+[.][0-9]+[.][0-9]+$"; then
			echo "Invalid Condor version: $VERSION" >&2
			exit 1
		fi
	fi
else
	# Validate package URL
	if ! echo "$PACKAGE_URL" | grep -q -E "(^gsiftp)|(^http)|(^ftp)"; then
		echo "Invalid package URL: $PACKAGE_URL" >&2
		exit 1
	fi
fi

# Check environment
if [ -z "${GLOBUS_LOCATION}" ]; then
	echo "GLOBUS_LOCATION environment variable not set" >&2
	exit 1
fi
source $GLOBUS_LOCATION/etc/globus-user-env.sh

# Determine package name if needed
if [ -z "${PACKAGE_URL}" ] && [ -z "$PACKAGE" ]; then

	# Determine package name
	os=`uname -s`
	case $os in
		Linux)
			# kernel and major versions only
			osver=`uname -r | cut -f1,2 -d.`
			arch=`uname -m`
			# change all the i486, i586, i686, etc to x86
			case $arch in
				i*86) arch="x86" ;;
			esac
			# glibc version, just major.minor
			glibc=`ldd --version | head -1 | cut -f4 -d" " | cut -f1,2 -d.`
			PACKAGE="${VERSION}-${arch}-${os}-${osver}-glibc${glibc}.tar.gz"
		;;
		SunOS)
			os="Solaris"
			arch=`uname -p`
			osver=`uname -r`
			case $osver in
				5.6) osver="2.6" ;;
				5.7) osver="7" ;;
				5.8) osver="8" ;;
				5.9) osver="9" ;;
				5.10) osver="10" ;;
			esac
			PACKAGE="${VERSION}-${arch}-${os}-${osver}.tar.gz"
		;;
		AIX)
			arch=`uname -p`
			osver="`uname -v`.`uname -r`"
			PACKAGE="${VERSION}-${arch}-${os}-${osver}.tar.gz"
		;;
		Darwin)
			os="MacOSX"
			arch=`uname -p`
			case $arch in
				powerpc64) arch="ppc64" ;;
				powerpc) arch="ppc" ;;
				i*86) arch="x86" ;;
			esac
			osver=`uname -r`
			case $osver in
				5.*) osver="10.1" ;;
				6.*) osver="10.2" ;;
				7.*) osver="10.3" ;;
				8.*) osver="10.4" ;;
				9.*) osver="10.5" ;;
				*) osver="unknown" ;;
			esac
			PACKAGE="${VERSION}-${arch}-${os}-${osver}.tar.gz"
		;;
		HP-UX)
			# arch will be either ia64 or PA-RISC
			arch=`uname -m`
			if [ "$arch" != "ia64" ]; then
				arch="PA-RISC"
			fi
			# uname -r => B.11.00
			osver=`uname -r | cut -f2,3 -d.`
			PACKAGE="${VERSION}-${arch}-${os}-${osver}.tar.gz"
		;;
		FreeBSD)
			arch=`uname -p`
			case $arch in
				i*86) arch="x86" ;;
			esac
			# Major version only
			# uname -r => 6.1-RELEASE-p15
			osver=`uname -r | cut -f1 -d- | cut -f1 -d.`
			PACKAGE="${VERSION}-${arch}-${os}-${osver}.tar.gz"
		;;
		*)
			arch=`uname -p`
			osver=`uname -r`
			PACKAGE="${VERSION}-${arch}-${os}-${osver}.tar.gz"
		;;
	esac
fi

# Locate tools
GUC="${GLOBUS_LOCATION}/bin/globus-url-copy"
if [ ! -x $GUC ]; then
	echo "Unable to locate globus-url-copy" >&2
	exit 1
fi
RLS="${GLOBUS_LOCATION}/bin/globus-rls-cli"
if [ ! -x $RLS ]; then
	echo "Unable to locate globus-rls-cli" >&2
	exit 1
fi

# If using RLS
PACKAGE_URLS=""
if [ -z "${PACKAGE_URL}" ]; then
	# Get list of urls from RLS
	RESULTS=`$RLS query lrc lfn $PACKAGE $RLS_URL`
	rc=$?
	if [ $rc != 0 ]; then
		echo "Unable to get package URL from RLS" >&2
		exit 1
	fi
	OLD_IFS=$IFS
	IFS="
"
	for RESULT in "$RESULTS"; do
		URL=`echo $RESULT | cut -f2- -d:`
		PACKAGE_URLS="$PACKAGE_URLS$URL "
	done
	IFS=$OLD_IFS
else
	# The package url is the list
	PACKAGE_URLS="${PACKAGE_URL}"
fi

# Download Condor package from one of the staging servers
PACKAGE_PATH=`pwd`/package.tar.gz
for PACKAGE_URL in ${PACKAGE_URLS}; do
	
	# Try globus-url-copy first
	$GUC ${PACKAGE_URL} file:${PACKAGE_PATH} 2>&1
	rc=$?
	
	# If globus-url-copy fails and the url is http or ftp, then try wget
	if [ $rc != 0 ] || [ ! -f ${PACKAGE_PATH} ] && 
	echo $URL | grep -q -E '(^http)|(^ftp)'; then
		wget -q -O ${PACKAGE_PATH} ${PACKAGE_URL} 2>&1
		rc=$?
	fi

	# Stop if we were successful
	if [ $rc = 0 ] && [ -f ${PACKAGE_PATH} ]; then 
		# Break out of loop
		break
	else
		# Remove any zero-length files that may have been created
		rm -f ${PACKAGE_PATH}
	fi
done

# If package could not be downloaded from any server
if [ ! -f ${PACKAGE_PATH} ]; then
	echo "Failed to retrieve binary worker package" >&2
	exit 1
fi

# Make install directory if it doesn't exist
if [ ! -d ${INSTALL_PATH} ]; then
	mkdir -p ${INSTALL_PATH}
	if [ ! -d ${INSTALL_PATH} ]; then
		echo "Unable to create remote install directory: ${INSTALL_PATH}" >&2
		exit 1
	fi
fi

# Install package
cd ${INSTALL_PATH}
if ! tar -xzf ${PACKAGE_PATH}; then
	echo "Failed to install Condor glidein package" >&2
	exit 1
fi

exit 0
