#!/bin/sh

# Usage
CMD=`basename $0`
usage ()
{
	echo """Usage: $CMD OPTIONS REQUIRED

REQUIRED

  -i | -installPath <path>
      The path where the Condor executables are installed.
      
OPTIONS

  -h | -help
      Display this usage message.
""" >&2
}

INSTALL_PATH=""

while [ $# -ge 1 ]; do
	case $1 in
		-i | -installPath) INSTALL_PATH=$2 ;;
		-h | -help) usage ; exit 1 ;;
		*) echo "Invalid argument $1" >&2 ; exit 1 ;;
	esac
	shift
	shift
done

if [ -z "${INSTALL_PATH}" ]; then
	echo "Missing -installPath" >&2
	exit 1
fi

# Remove installation directory
if [ -d ${INSTALL_PATH} ]; then
	rm -rf ${INSTALL_PATH}
	rc=$?
	if [ $rc -ne 0 ]; then
		echo "Unable to delete install directory: ${INSTALL_PATH}" >&2
		exit 1
	fi
fi

exit 0